version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: audiencly-backend
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - DATABASE_URL=${DATABASE_URL:-postgresql://audiencly:audiencly_secure_password@db:5432/audiencly}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - MS_TENANT_ID=${MS_TENANT_ID}
      - MS_CLIENT_ID=${MS_CLIENT_ID}
      - MS_CLIENT_SECRET=${MS_CLIENT_SECRET}
      - MS_REDIRECT_URI=${MS_REDIRECT_URI:-http://localhost:5556/auth/callback}
    command: ["python","-m","uvicorn","main:app","--host","0.0.0.0","--port","8002"]
    working_dir: /app
    ports:
      - "5555:8002"
    depends_on:
      - db
    networks: [appnet]

  frontend:
    build:
      context: ./frontend
    container_name: audiencly-frontend
    environment:
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:5559
    working_dir: /app
    ports:
      - "5556:3000"
    depends_on:
      - backend
    networks: [appnet]

  db:
    image: postgres:16-alpine
    container_name: audiencly-db
    environment:
      - POSTGRES_USER=audiencly
      - POSTGRES_PASSWORD=audiencly_secure_password
      - POSTGRES_DB=audiencly
    ports:
      - "5557:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [appnet]

  nginx:
    image: nginx:alpine
    container_name: audiencly-nginx
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5558:5558"
      - "5559:5559"
    depends_on:
      - backend
      - frontend
    networks: [appnet]

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
